### ISSUE TITLE
Errors in compile with CEP 4.7

### ISSUE THREAD

**Issue by jordankrim** [CommonEvaluationPlatform/CEP#42]
I believe I am trying to do a pre-compile of the Chipyard scala files and get these errors:

[info] compiling 4 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/target/scala-2.13/classes ...
[info] compiling 3 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/target/scala-2.13/classes ...
[info] compiling 42 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/constellation/target/scala-2.13/classes ...
[info] compiling 3 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/target/scala-2.13/classes ...
[info] compiling 14 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/target/scala-2.13/classes ...
[info] compiling 52 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/testchipip/target/scala-2.13/classes ...
[info] compiling 55 Scala sources to /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/gemmini/src/target/scala-2.13/classes ...
[info] Ignoring duplicate plugin chiselplugin (chisel3.internal.plugin.ChiselPlugin)
[error] **/mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/ConfigFragments.scala:6:12: object chipsalliance is not a member of package org
[error] import org.chipsalliance.cde.config.{Field, Parameters, Config}**
[error]            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:22:12: object chipsalliance is not a member of package org
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:17:12: object chipsalliance is not a member of package org
[error] import org.chipsalliance.cde.config._
[error] import org.chipsalliance.cde.config.{Parameters, Config, Field}
[error]            ^
[error]            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:23:8: not found: object freechips
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:18:8: not found: object freechips
[error] import freechips.rocketchip.subsystem._
[error]        ^
[error] import freechips.rocketchip.subsystem._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/ConfigFragments.scala:13:69: not found: type Config
[error] class WithNVDLA(config: String, synthRAMs: Boolean = false) extends Config((site, here, up) => {
[error]                                                                     ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:19:8: not found: object freechips
[error] import freechips.rocketchip.rocket._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:24:8: not found: object freechips
[error] import freechips.rocketchip.devices.tilelink._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:25:8: not found: object freechips
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:20:8: not found: object freechips
[error] import freechips.rocketchip.tile._
[error]        ^
[error] import freechips.rocketchip.diplomacy._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:27:8: not found: object freechips
[error] import freechips.rocketchip.rocket._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:28:42: not found: type Config
[error] class WithNIbexCores(n: Int = 1) extends Config((site, here, up) => {
[error]                                          ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:28:8: not found: object freechips
[error] import freechips.rocketchip.subsystem.{RocketCrossingParams}
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:29:8: not found: object freechips
[error] import freechips.rocketchip.tilelink._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:30:8: not found: object freechips
[error] import freechips.rocketchip.interrupts._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:31:8: not found: object freechips
[error] import freechips.rocketchip.util._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:32:8: not found: object freechips
[error] import freechips.rocketchip.tile._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:15:12: object chipsalliance is not a member of package org
[error] import org.chipsalliance.cde.config.{Field, Parameters, Config}
[error]            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/cva6/src/main/scala/cva6/CVA6CoreBlackbox.scala:33:8: not found: object freechips
[error] import freechips.rocketchip.amba.axi4._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:16:8: not found: object freechips
[error] import freechips.rocketchip.subsystem.{BaseSubsystem, PeripheryBusKey, PBUS, MBUS, FBUS}
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:17:12: object chipsalliance is not a member of package org
[error] import org.chipsalliance.diplomacy.lazymodule._
[error]            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:18:8: not found: object freechips
[error] import freechips.rocketchip.diplomacy.{SimpleDevice, IdRange, TransferSizes, RegionType, AddressSet}
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:19:8: not found: object freechips
[error] import freechips.rocketchip.regmapper.{HasRegMap, RegField, RegFieldGroup, RegFieldDesc}
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:20:8: not found: object freechips
[error] import freechips.rocketchip.tilelink._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/ConfigFragments.scala:13:93: no arguments allowed for nullary constructor Object: (): Object
[error] class WithNVDLA(config: String, synthRAMs: Boolean = false) extends Config((site, here, up) => {
[error]                                                                                             ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/ibex/src/main/scala/ConfigMixins.scala:28:66: no arguments allowed for nullary constructor Object: (): Object
[error] class WithNIbexCores(n: Int = 1) extends Config((site, here, up) => {
[error]                                                                  ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:5:12: object chipsalliance is not a member of package org
[error] import org.chipsalliance.cde.config._
[error]            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:6:8: not found: object freechips
[error] import freechips.rocketchip.diplomacy._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:7:8: not found: object freechips
[error] import freechips.rocketchip.amba.axi4._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:8:8: not found: object freechips
[error] import freechips.rocketchip.amba.apb._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:9:8: not found: object freechips
[error] import freechips.rocketchip.tilelink._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:10:8: not found: object freechips
[error] import freechips.rocketchip.interrupts._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:11:8: not found: object freechips
[error] import freechips.rocketchip.subsystem._
[error]        ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:34:37: not found: type Field
[error] case object PeripheryAESKey extends Field[Seq[COREParams]](Nil)
[error]                                     ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:34:60: no arguments allowed for nullary constructor Object: (): Object
[error] case object PeripheryAESKey extends Field[Seq[COREParams]](Nil)
[error]                                                            ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:38:35: not found: type BaseSubsystem
[error] trait CanHavePeripheryAES { this: BaseSubsystem =>
[error]                                   ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:39:17: not found: value p
[error]   val aesnode = p(PeripheryAESKey).map { params =>
[error]                 ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:42:16: not found: value locateTLBusWrapper
[error]     val pbus = locateTLBusWrapper(PBUS)
[error]                ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:42:35: not found: value PBUS
[error]     val pbus = locateTLBusWrapper(PBUS)
[error]                                   ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:43:16: not found: value locateTLBusWrapper
[error]     val mbus = locateTLBusWrapper(MBUS)
[error]                ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:43:35: not found: value MBUS
[error]     val mbus = locateTLBusWrapper(MBUS)
[error]                                   ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:44:16: not found: value locateTLBusWrapper
[error]     val fbus = locateTLBusWrapper(FBUS)
[error]                ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/mitll-blocks/src/main/scala/aes.scala:44:35: not found: value FBUS
[error]     val fbus = locateTLBusWrapper(FBUS)
[error]                                   ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:21:66: not found: type LazyModule
[error] class NVDLA(params: NVDLAParams)(implicit p: Parameters) extends LazyModule {
[error]                                                                  ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:21:46: not found: type Parameters
[error] class NVDLA(params: NVDLAParams)(implicit p: Parameters) extends LazyModule {
[error]                                              ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:28:23: not found: type SimpleDevice
[error]   val dtsdevice = new SimpleDevice("nvdla",Seq("nvidia,nv_" + params.config))
[error]                       ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:31:21: not found: value TLIdentityNode
[error]   val dbb_tl_node = TLIdentityNode()
[error]                     ^
[error] /mnt/data/projects/avalon/jkrim/cep_v4_7_test_branch_clone/CEP/generators/nvdla/src/main/scala/devices/nvdla/NVDLA.scala:34:22: not found: value AXI4MasterNode
[error]   val dbb_axi_node = AXI4MasterNode(
[error]                      ^
... 

I get many more errors following this, but didn't want to swamp the issue request.

**Comment by bchetwynd** [comment]
It sounds like your repository did not initialize properly.  I just checked out CEP v4.7, setup conda per the instructions, and ran the following command w/o issue:
`./build-setup.sh --skip-firesim --skip-marshal`

What specific command are you running?

**Comment by jordankrim** [comment]
Here's how I initialized the CEP.  I have a Git repo that I clone.  It creates an area where there is a .git/config with this in it:

[submodule "CEP"]
	active = true
	url = https://github.com/CommonEvaluationPlatform/CEP.git

Also, the file .gitmodules has this:

[submodule "CEP"]
	path = CEP
	url = https://github.com/CommonEvaluationPlatform/CEP.git

From this directory where there is a sub-directory named CEP, I execute:

git submodule update --init --recursive

Then I execute a script that does this:

conda install -n base conda-libmamba-solver
conda config --set solver libmamba
conda install -n base conda-lock==1.4.0
#conda install -c conda-forge cryptopp
#Activate the base conda environment
conda activate base
conda config --set auto_activate_base false #don't automatically run the base environent upon execution of .bashrc
conda init bash #Be sure bash is correctly configured with conda (other base environ deactivation will hang) 

It then does:

cd CEP

and then it does:

./build-setup.sh

I didn't do the skip like you show but does that matter or is there something else in my procedure that looks wrong?

**Comment by bchetwynd** [comment]
`./build-setup.sh ` automatically initializes the submodules.  You shouldn't do it manually.

**Comment by jordankrim** [comment]
I am not sure what you mean by manually.   When I clone my repo, there is a subdirectory there called CEP but it is empty.  I cannot go into it and execute ./build-setup.sh because is obviously doesn't exist so I have a chicken and egg problem and I'm not sure what to do to fix it.  By doing the git submodule update --init --recursive from the directory containing the CEP subdirectory it populates the CEP.   Is this what you mean by manually?   What is the proper procedure to get the CEP populated?

**Comment by bchetwynd** [comment]
When you clone the directly, don't do the `git submodule update --init --recursive`.  The submodules get initialized when you run the `./build-setup.sh` script.

If the CEP is a submodule of your repo, then I am not a 100% sure what you are doing.  Regardless, don't initialize the CEP submodules manually using the aforementioned git command.

**Comment by jordankrim** [comment]
If I don't use the git submodule update --init --recursive then how am I supposed to get the ./build-setup.sh when it doesn't exist?
Are you suggesting that I simply go to the directory where the empty CEP subdirectory is and clone it using:
git clone https://github.com/CommonEvaluationPlatform/CEP.git or is there another way to get the  build-setup.sh script?

**Comment by bchetwynd** [comment]
I don't know why your clone doesn't work as expected.  

If you run `git clone https://github.com/CommonEvaluationPlatform/CEP.git` it should create a CEP subdirectory with the repo (not submodules) populated.
